### ISSUE TITLE
errors loading

### ISSUE THREAD

**Issue by mtklr** [srcery-colors/srcery-vim#88] opened 2022-12-17 21:33 UTC
hi,

I love Srcery! Having some issues recently though.

On my end, commit 34c87e4df4d19b47af3dbfa7f040781293b2b6de works without issue from `~/.vim/pack/plugin/opt/srcery-vim` or `~/.vim/pack/plugin/start/srcery-vim`.

Checking out the commit after that (27d66bc14636889a11021feecb13d38187195b22) I get a bunch of errors like this:

```
line  240:
E121: Undefined variable: g:srcery_bg_passthrough
E15: Invalid expression: g:srcery_bg_passthrough == 1 && !has('gui_running')
line  261:
E121: Undefined variable: s:bright_white
E116: Invalid arguments for function <SNR>3_HL
line  275:
E121: Undefined variable: s:bright_black
E116: Invalid arguments for function <SNR>3_HL
```

I'm testing this with a minimal `.vimrc`:

```
colorscheme srcery
```

`nvim` doesn't seem to have this issue, with a minimal `.config/nvim/init.vim`:

```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

Though it only works if using `~/.vim/pack/plugin/start/srcery-vim`.

I've never had a problem until I pulled from github today and received these errors.

nvim version: 0.8.1
vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 14 2021 20:35:46)
(this is on macos)

(Maybe I should forget about vim and stick to nvim)

Thanks,
matt

**Comment by Guergeiro** [comment] 2022-12-17 23:31
Hey matt!

Thanks for pointing your issue. In your `.vimrc`, using vim, not neovim, could you try:
```
packadd! srcery-vim
colorscheme srcery
```

Report back if possible 🙂

**Comment by mtklr** [comment] 2022-12-18 01:08
Hi,

Yes, with `srcery-vim` in `~/.vim/pack/plugin/opt/srcery-vim` and `packadd! srcery-vim`, this does work.

`~/.vim/pack/plugin/start/srcery-vim` with or without `packadd!` does not work.

Thanks:)

**Comment by Guergeiro** [comment] 2022-12-18 11:23
Okay, so this is because of how Vim packages work. We need to update documentation to explain how to install srcery with natives packages.

What do you think @roosta @MindTooth ?

**Comment by Guergeiro** [comment] 2022-12-18 12:15
> `~/.vim/pack/plugin/start/srcery-vim` with or without `packadd!` does not work.

I can't reproduce this... If I move from `opt` to `start` and remove `packadd!` everything is loaded correctly.

**Comment by MindTooth** [comment] 2022-12-18 14:13
I'm sorry to hear that it might have caused issues with Vim and manually/`packadd` setups.

From the official help ([`:help pack-add`](https://vimhelp.org/repeat.txt.html#pack-add)), it should reside under `pack/*/opt/srcery-vim`.  If that does not work, we need to debug this.

@Guergeiro I'll review your pull request.  Hopefully we can provide a fix. 😄

**Comment by mtklr** [comment] 2022-12-18 14:45
Sorry to cause problems, this seems like "user error" (me) likely, though I just tried clearing any/all shell customizations, started with fresh `.vim` directory, re-cloned srcery, and still getting errors.

(Could be weird disk/OS related thing on my end maybe.)

Thanks for your time looking into it. I can deal with workarounds for now.

**Comment by Guergeiro** [comment] 2022-12-18 15:18
@mtklr it was definitely our fault! Let me suggest another thing. Can you try setting your `runtimepath` in your `.vimrc` like you did for neovim? In this case to try to load on the `.vim/pack/*/start` directory, not the `opt`.

**Comment by mtklr** [comment] 2022-12-18 16:56
Sure.

with `.vim/pack/plugin/start/srcery-vim`, and this `~/.vimrc`:

```vim
set runtimepath^=~/.vim "runtimepath+=~/.vim/after
let &packpath = &runtimepath
" also tried just this:
" set runtimepath+=~/.vim
colorscheme srcery
```

Same errors as mentioned - (checking out 34c87e4 it works. From the commit after this (27d66bc) it does not work).

**Comment by Guergeiro** [comment] 2022-12-18 17:44
In the case of the "manual" approach of the readme, its basically the same issue. One user already opened an issue #89

**Comment by mtklr** [comment] 2022-12-18 21:32
> In the case of the "manual" approach of the readme, its basically the same issue. One user already opened an issue #89 

Ok, thanks - sorry for the extra work - should I close this, then?

**Comment by Guergeiro** [comment] 2022-12-18 23:38
No need @mtklr we will close this in our upcoming pr #90 
Thanks for finding this issue!

**Closed** 2022-12-20 11:23 UTC
