### ISSUE TITLE
Visual selection doesn't highlight last character in gvim

### ISSUE THREAD

**Issue by davidnash** [srcery-colors/srcery-vim#24] opened 2018-08-22 01:27 UTC
First of all: I love, love, LOVE this colorscheme!

But a minor gripe - if I'm selecting in visual mode (or with the mouse), the last character of the selection doesn't get highlighted. Which mean that I'm actually selecting on character extra than it appears.

So for example if the word is 'appears', and I've highlighted up to the 'r', the 's' is actually selected too.

Not a huge issue, but big enough to be annoying.

Thanks again for such an awesome colorscheme!

**Comment by roosta** [comment] 2018-08-22 08:25
Glad you like it! :) I'll look into it. My guess is that its a problem where the cursor inverts an already inverted selection returning it back to normal. I've been toying with the idea of just setting the cursor to a static color to avoid issues similar to this.

I'm not able to reproduce the issue though, if you have any more information about the terminal emulator you're using and what the cursor settings are in that, that would be helpful.

**Comment by roosta** [comment] 2018-08-22 08:29
Ah, I was able to produce the issue in gvim. I'll see about patching it up later today.

**Comment by roosta** [comment] 2018-08-22 15:52
Ok pushed a potential fix, let me know how it worked for you
1c9c8db

**Comment by davidnash** [comment] 2018-08-22 21:48
Works great! And thanks for looking at it so quickly - you rock!

**Comment by roosta** [comment] 2018-08-23 08:35
np :) I'm closing this issue then.

**Closed by roosta** 2018-08-23 08:35 UTC
