### ISSUE TITLE
Colours come out with when running in NeoVim with termguicolors.

### ISSUE THREAD

**Issue by xfbs** [srcery-colors/srcery-vim#36] opened 2019-05-21 12:00 UTC
For some reason, when using NeoVim, and having `set termguicolors` enabled, the colors don't come out right. Here's what I mean:

This is in NeoVim, with `notermguicolors` set. Looks as it should.
![notermguicolors](https://user-images.githubusercontent.com/786420/58094296-a00aff00-7bd0-11e9-939e-9951e4b5e605.png)

This is in NeoVim, with `termguicolors` set. Looks slightly wrong. Note especially the reddish colour of the "bright_white".
![termguicolors](https://user-images.githubusercontent.com/786420/58094292-9d100e80-7bd0-11e9-88a2-cd1cd0237866.png)

**Comment by roosta** [comment] 2019-05-21 12:20
Could this be related to #35? I'll have a look at this later today.

**Comment by xfbs** [comment] 2019-05-21 14:21
As it turns out, this does not seem to be a bug with srcery! So here's what (I think) I figured out. Normally, when running Vim, the colorscheme loads something like

```vim
hi Normal ctermfg=15 ctermbg=0 guifg=#FCE8C3 guibg=#1C1B19
```

What Vim does with this is that it takes the `ctermfg` and `ctermbg` values and uses it to color text, by sending ANSI escape sequences like this:

    printf "\033[38;5;15mforeground color\033[0m"

There are 256 colors available to use like this. This works. The `guibg` and `guifg` values are only used for GUI clients. However, in NeoVim, if I set `termguicolors`, then it does something a bit different. It uses the hex color values for the GUI in the terminal. Some terminals support arbitrary RBG colors using a different ANSI escape sequence. The foreground color, #FCE8C3, would be encoded like this:

    printf "\033[38;2;252;232;195mTEST TEST TEST\033[0m"

However, this is not supported by Terminal.app. I'm guessing that `tmux` sensed this and basically faked the colours by converting them to the 256 color space, which lead to them being off? Not entirely sure.

**Comment by roosta** [comment] 2019-05-22 09:37
Could be it, Emacs does something similar when presented with color hexes in terminal. It tries to conform it to the 256 color space. I'm not sure its tmux that's doing it, I'm guessing its Neovim. Either way this is expected behavior. Have you tried the same thing in a true color terminal?

**Comment by xfbs** [comment] 2019-05-22 17:59
I actually confirmed it's tmux that is mapping the 24-bit colors. If I run NeoVim in a 24-bit capable terminal, it works fine with both `termguicolors` and `notermguicolors`:

<img width="710" alt="Screenshot 2019-05-22 at 19 46 18" src="https://user-images.githubusercontent.com/786420/58196361-6dddc800-7cca-11e9-8fcf-6890b2966a23.png">
<img width="710" alt="Screenshot 2019-05-22 at 19 46 24" src="https://user-images.githubusercontent.com/786420/58196365-6dddc800-7cca-11e9-9029-61b858fa6ec2.png">

I found a script to generate a rainbow, and it looks like this:

<img width="590" alt="Screenshot 2019-05-22 at 19 29 35" src="https://user-images.githubusercontent.com/786420/58195412-34a45880-7cc8-11e9-86ac-2aba9ad1d03a.png">

However, when running it in tmux, the output looks like such:

<img width="590" alt="Screenshot 2019-05-22 at 19 29 27" src="https://user-images.githubusercontent.com/786420/58195447-438b0b00-7cc8-11e9-8ef7-b7cdf0275f1f.png">

It's possible to force tmux not to do this. Tmux is actually the reason that running NeoVim in Terminal.app with `termguicolors` worked in first place: Terminal.app doesn't support 24-bit colors. So I guess the takeaway is: don't use termguicolors. However:

*If you have a 24-bit capable terminal emulator and you want to use 24-bit colors*

Force `tmux` to pass through 24-bit color codes (unless it detects that your terminal does this)

```tmux
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

Tell vim to use 24-bit colors

```vim
set termguicolors
```

I also had to set TERM manually. It's kinda messy. But it works:

<img width="710" alt="Screenshot 2019-05-22 at 19 55 33" src="https://user-images.githubusercontent.com/786420/58197055-c2ce0e00-7ccb-11e9-8ea1-acc5b62f7b40.png">
<img width="710" alt="Screenshot 2019-05-22 at 19 55 24" src="https://user-images.githubusercontent.com/786420/58197056-c2ce0e00-7ccb-11e9-9000-5384fde995e2.png">

Maybe this could be useful to someone? Not sure. Interesting to learn how this stuff all works, tho.

**Comment by MindTooth** [comment] 2019-05-22 18:04
This is with Terminal.app?  With kitty I have no issues AFAIK.  The rainbow shows fine.

With `kitty` I only set:
```tmux
set -g default-terminal 'xterm-kitty'
```

**Comment by roosta** [comment] 2019-05-22 18:14
turns out I got this snippet in my tmux conf
```tmux
set -ga terminal-overrides ",xterm-termite:Tc"
set -g default-terminal "tmux-256color"
```
no issue with the rainbow. Seems I just copy pasted this from the arch linux wiki, and promptly forgot about it. Should we add a note in the readme about this maybe?

**Comment by MindTooth** [comment] 2019-05-22 18:24
That code is a standard snippet I've seen a couple of places..  A notice could help more people to detect it.

**Comment by roosta** [comment] 2019-05-23 17:58
Added, close this?

**Closed** 2019-05-28 12:56 UTC
